In [4]:
import pandas as pd
import os
from sklearn.model_selection import train_test_split
import pickle

In [3]:
BATCH_SIZE = 10

# Create tokenizer
DATA_FOLDER = 'data'
MODEL_FOLDER = 'models'
EXPERIMENT_FOLDER = 'experiment'

VALUES = ['ACHIEVEMENT', 'BENEVOLENCE', 'CONFORMITY', 'HEDONISM', 'POWER', 'SECURITY', 'SELF-DIRECTION', 'STIMULATION', 'TRADITION', 'UNIVERSALISM']


# Create datasets
train_datasets = []    
test_datasets = []
dataset = pd.DataFrame()

for value in VALUES:
    FILE = value + '.csv'
    train_split = .8
    df = pd.read_csv(os.path.join(os.getcwd(), DATA_FOLDER, FILE))
    df["value"] = value
    dataset = pd.concat([dataset,df[["uid", "scenario", "label", "value"]]])

#dataset is a dataframe containing every scenario, their associated value and their label
dataset.describe(include="all")

                 uid               scenario         label        value
count   21374.000000                  21374  21374.000000        21374
unique           NaN                  17965           NaN           10
top              NaN  not backing up my mom           NaN  BENEVOLENCE
freq             NaN                      5           NaN         7667
mean    35837.167072                    NaN     -0.318471          NaN
std     24540.696705                    NaN      0.761050          NaN
min        18.000000                    NaN     -1.000000          NaN
25%     14961.250000                    NaN     -1.000000          NaN
50%     31239.500000                    NaN      0.000000          NaN
75%     54489.750000                    NaN      0.000000          NaN
max     82379.000000                    NaN      1.000000          NaN

In [5]:
y = dataset[["label", "value"]]
X = dataset["scenario"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(17099,) (4275,) (17099, 2) (4275, 2)